repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.40.0
    hooks:
      - id: typos
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        entry: cargo fmt -- --config "unstable_features=true,imports_granularity=Crate,group_imports=StdExternalCrate,format_code_in_doc_comments=true"
        language: rust
        pass_filenames: false
        types_or: [rust, toml]
      - id: clippy-no-default-features
        name: clippy-no-default-features
        entry: cargo clippy --no-default-features --all-targets -- -D warnings
        language: rust
        pass_filenames: false
        types_or: [rust, toml]
      - id: clippy-all-features
        name: clippy-all-features
        entry: cargo clippy --all-features --all-targets -- -D warnings
        language: rust
        pass_filenames: false
        types_or: [rust, toml]