name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: [--no-default-features, --all-features]
    steps:
      - uses: actions/checkout@v6
      - name: rustfmt
        run: cargo fmt -- --config "unstable_features=true,imports_granularity=Crate,group_imports=StdExternalCrate,format_code_in_doc_comments=true"
      - name: clippy
        run: cargo clippy ${{ matrix.features }} --all-targets -- -D warnings
      - name: test
        run: cargo test ${{ matrix.features }}
      - name: install miri
        run: rustup install nightly && rustup +nightly component add miri
      - name: miri
        run: cargo +nightly miri test ${{ matrix.features }}
      #      - name: Install cargo-llvm-cov
      #        uses: taiki-e/install-action@cargo-llvm-cov
      #      - name: code coverage
      #        run: cargo +nightly llvm-cov ${{ matrix.features }} --fail-under-functions 90 --fail-under-lines 90 --fail-under-regions 90
      - name: check doc
        run: cargo doc
        env:
          RUSTDOCFLAGS: "-Dwarnings"
  benchmark:
    needs: test
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: benchmark
        run: cargo bench -- --min-time 1
